// next/src/app/components/CardEvent.jsx
'use client'

import React, { useState } from 'react';
import MapPin from './Icons/MapPin';
import Calendar from './Icons/Calendar';
import Users from './Icons/Users';
import Heart from './Icons/Heart';
import HeartFill from './Icons/HeartFill';

const CardEvent = ({ image, name, location, date, people }) => {
    const [liked, setLiked] = useState(false);

    const toggleLike = () => {
        setLiked(!liked);
    };

    return (
        <button className='relative w-full h-56 rounded-xl overflow-hidden'>
            <img className='w-full h-full brightness-[.7] object-cover' src={image} alt="" />
            <div className='absolute bottom-2 left-2'>
                <h2 className='text-white text-xl font-semibold'>{name}</h2>
                <p className='text-white flex items-center gap-1'><MapPin size="18" />{location}</p>
                <p className='text-white flex items-center gap-1'><Calendar size="18" />{date}</p>
                <p className='text-white flex items-center gap-1'><Users size="18" />{people} personas</p>
            </div>
            <button
                className={`absolute bottom-2 right-2 p-1 rounded-lg ${liked ? 'bg-red-500 hover:bg-red-700' : 'bg-green-500 hover:bg-green-700'}`}
                onClick={toggleLike}
            >
                {liked ? <HeartFill size="20" /> : <Heart size="20" />}
            </button>
        </button>
    );
};

export default CardEvent;

// nuxt/components/CardEvent.vue
<template>

    <div class='relative w-full h-56 rounded-xl overflow-hidden'>
        <img class='w-full h-full brightness-[.4] object-cover' :src="JSON.parse(event.images)[2]" alt="" />,
        <div class='absolute bottom-2 left-2'>
            <h2 class='text-white text-xl font-semibold text-left'>{{ event.event }}</h2>
            <p class='text-white flex items-center gap-1'>
                <IconsMapPin class="size-4" />{{ event.city }}
            </p>
            <p class='text-white flex items-center gap-1'>
                <IconsCalendar class="size-4" />{{ event.date }}
            </p>
            <p class='text-white flex items-center gap-1'>
                <IconsUsers class="size-4" />300 inscritos
            </p>
        </div>

        <button v-if="liked" class="absolute bottom-2 right-2 p-1 rounded-lg text-white bg-red-500 hover:bg-red-700"
            @click="toggleLike(eventId)">
            <IconsHeartFill class="size-5" />
        </button>

        <button v-if="!liked" class="absolute bottom-2 right-2 p-1 rounded-lg text-white bg-green-500 hover:bg-green-700"
            @click="toggleLike(eventId)">
            <IconsHeart class="size-5" />
        </button>

    </div>

</template>

<script>

export default {
    data() {
        return {
            liked: false
        }

    },
    props: {
        event: {
            type: Object,
            required: true
        }
    },
    methods: {
        toggleLike() {
            this.liked = !this.liked;
        }
    },
    mounted() {
        console.log(this.event);
    }
}
</script>

<style scoped></style>
