// next/src/app/events/[id]/page.jsx
'use client'
import React, { useEffect, useState } from 'react'
import axios from 'axios';
import Loader from '../../components/Loader'

const Page = ({ params }) => {
  const { id } = params;
  const [datos, setDatos] = useState(null);

  useEffect(() => {
    const cargarConcierto = async () => {
      console.log("2");
      try {
        const response = await axios.get(`http://localhost:8000/api/events/${id}`);
        console.log(response);
        setDatos(response.data.event);
      } catch (error) {
        console.error(`Error al cargar el concierto con id ${id}:`, error);
      }
    }

    cargarConcierto();
  }, [id]);

  console.log("1");

  if (!datos) {
    return <div className='flex w-full h-screen justify-center items-center'><Loader /></div>;
  }

  console.log("3");

  return (
    <>
      <img src={JSON.parse(datos.images)[2]} className='w-full h-[218px] object-cover' alt="" />
      <article className='w-[80%] mx-auto flex flex-col gap-2'>
        <p className='text-xs text-[#A4A4A4]'>Concierto</p>
        <h1 className='text-2xl font-bold'>{datos.event}</h1>
        <h2 className='font-semibold text-base'>{datos.city}</h2>
        <h2 className='font-semibold text-base'>{datos.venue}</h2>
        <h3 className='text[#CACACA] text-base'>2.487 personas inscritas</h3>
        <div className='w-full h-[2px] bg-[#888888]'></div>
      </article>
    </>
  )
}

export default Page

// nuxt/pages/post/[id].vue
<template>
    <section>
        <header class="w-[90%] mx-auto py-4 flex gap-5 items-center">
            <NuxtLink to="/home">
                <IconsLeftArrow class="size-6 bg-black rounded-full bg-opacity-60" />
            </NuxtLink>
            <h1 class="text-xl font-bold">Post</h1>
        </header>
        <main class="w-[90%] mx-auto py-2">
            <header class="flex gap-3 items-center mb-3">
                <img class="size-12 rounded-full object-cover"
                    src="https://hips.hearstapps.com/hmg-prod/images/phineas-and-ferb-1590490321.jpg" alt="">
                <div>
                    <h2 class="font-bold">User name</h2>
                    <p class="text-sm text-gray-400">@nickname</p>
                </div>
            </header>
            <article>
                <p>{{ post.content }}</p>
                <img class="rounded" src="https://h2.gifposter.com/bingImages/OceanDrive_EN-US3763740504_1920x1080.jpg"
                    alt="">
            </article>
            <footer>
                
            </footer>
        </main>
    </section>



</template>

<script>
import axios from 'axios'
export default {
    data() {
        return {
            postId: this.$route.params.id,
            post: {},
        }
    },

    methods: {
        async getPost() {
            try {
                const response = await axios.get(`http://localhost:8086/posts/${this.postId}`)
                this.post = response.data;
                console.log(this.post)
            } catch (error) {
                console.error(error)
            }
        }
    },

    created() {
        this.getPost()
    }
}
</script>
