// next/src/app/components/Header.jsx
import React from 'react'
import Link from 'next/link';

const Header = () => {
  return (
    <header className='w-[90%] py-4 mx-auto flex justify-between'>
      <h1 className='text-2xl font-bold text-white uppercase'>Spottunes</h1>
      <Link href='/login'>Inicia sessió</Link>
    </header>
  )
}

export default Header

// nuxt_deprecated/components/Header.vue
<template>
    <header class='w-[90%] py-4 mx-auto flex justify-between'>
      <h1 class='text-2xl font-bold text-white uppercase'>Spottunes</h1>
      <NuxtLink to="/login" class="text-white">Inicia sessió</NuxtLink>
    </header>
</template>

<script>
    export default {
        
    }
</script>

<style lang="scss" scoped>

</style>
