// next/src/app/components/Hero.jsx
import React from 'react'
import ButtonCTA from './ButtonCTA'

const Hero = () => {
    return (
        <>
            <section className='flex flex-col items-center justify-center h-[90dvh] gap-5'>
                <h2 className='text-white text-3xl font-bold text-center uppercase'>Troba el teu company de concerts perfecte</h2>
                <p className='text-white text-center text-pretty'>Connecta la teva passió per la música amb noves amistats. Descobreix concerts èpics i companys de concerts inoblidables amb la nostra aplicació.</p>
                <ButtonCTA>Veure concerts</ButtonCTA>
            </section>
        </>
    )
}

export default Hero

// nuxt_deprecated/components/Hero.vue
<template>
    <section class='flex flex-col items-center justify-center h-[90dvh] gap-5'>
        <h2 class='text-white text-3xl font-bold text-center uppercase'>Troba el teu company de concerts perfecte
        </h2>
        <p class='text-white text-center text-pretty'>Connecta la teva passió per la música amb noves amistats.
            Descobreix concerts èpics i companys de concerts inoblidables amb la nostra aplicació.</p>
        <ButtonCTA>Veure concerts</ButtonCTA>
    </section>
</template>

<script>
export default {

}
</script>

<style lang="scss" scoped></style>
