// next/src/app/components/PostsProfile.jsx
import React from 'react'

const PostProfile = () => {
    return (
        <section className='grid grid-cols-3 gap-2 px-6'>
            <article className='h-40 overflow-hidden rounded-lg'>
                <img className='w-full h-full object-cover' src="https://www.shutterstock.com/image-photo/crowd-partying-stage-lights-live-600nw-2297236461.jpg" alt="" />
            </article>
            <article className='h-40 overflow-hidden rounded-lg'>
                <img className='w-full h-full object-cover' src="https://cdn.pixabay.com/photo/2015/11/22/19/04/crowd-1056764_640.jpg" alt="" />
            </article>
            <article className='h-40 overflow-hidden rounded-lg'>
                <img className='w-full h-full object-cover' src="https://www.tarracoarena.com/wp-content/uploads/2023/06/2023-Concierto-TarracoArena.jpg" alt="" />
            </article>

            <article className='h-40 overflow-hidden rounded-lg'>
                <img className='w-full h-full object-cover' src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSA3YA0wHEZ_3WW5cXMACgP5gG4Dmf-2QplwgAZUvf8bwN627FWDod6k7bB3l2Sx2tfy6U&usqp=CAU" alt="" />
            </article>
            <article className='h-40 overflow-hidden rounded-lg'>
                <img className='w-full h-full object-cover' src="https://d1bvpoagx8hqbg.cloudfront.net/originals/festival-cabo-plata-af3046d6531984e4bda4175fc9beb113.jpg" alt="" />
            </article>
            <article className='h-40 overflow-hidden rounded-lg'>
                <img className='w-full h-full object-cover' src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRHCWWFoH41Wm59POvxQPtOWT6XmHovcViXTYe1HRVNol6cZorKouAmj4lOkOxtwnR3Agc&usqp=CAU" alt="" />
            </article>

            <article className='h-40 overflow-hidden rounded-lg'>
                <img className='w-full h-full object-cover' src="https://www.lavozdelsur.es/uploads/s1/11/22/25/9/1658619294066-01.jpeg" alt="" />
            </article>
            <article className='h-40 overflow-hidden rounded-lg'>
                <img className='w-full h-full object-cover' src="https://publicacionesdelsur.b-cdn.net/articulos/articulos-1027817.jpg" alt="" />
            </article>
            <article className='h-40 overflow-hidden rounded-lg'>
                <img className='w-full h-full object-cover' src="https://www.shutterstock.com/image-photo/two-young-woman-having-great-600nw-2195333383.jpg" alt="" />
            </article>
        </section>
    )
}

export default PostProfile

// nuxt_deprecated/components/PostsProfile.vue
<template>
    <section className='grid grid-cols-3 gap-2 px-6'>
        <article className='h-40 overflow-hidden rounded-lg'>
            <img className='w-full h-full object-cover'
                src="https://www.shutterstock.com/image-photo/crowd-partying-stage-lights-live-600nw-2297236461.jpg"
                alt="" />
        </article>
        <article className='h-40 overflow-hidden rounded-lg'>
            <img className='w-full h-full object-cover'
                src="https://cdn.pixabay.com/photo/2015/11/22/19/04/crowd-1056764_640.jpg" alt="" />
        </article>
        <article className='h-40 overflow-hidden rounded-lg'>
            <img className='w-full h-full object-cover'
                src="https://www.tarracoarena.com/wp-content/uploads/2023/06/2023-Concierto-TarracoArena.jpg" alt="" />
        </article>

        <article className='h-40 overflow-hidden rounded-lg'>
            <img className='w-full h-full object-cover'
                src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSA3YA0wHEZ_3WW5cXMACgP5gG4Dmf-2QplwgAZUvf8bwN627FWDod6k7bB3l2Sx2tfy6U&usqp=CAU"
                alt="" />
        </article>
        <article className='h-40 overflow-hidden rounded-lg'>
            <img className='w-full h-full object-cover'
                src="https://d1bvpoagx8hqbg.cloudfront.net/originals/festival-cabo-plata-af3046d6531984e4bda4175fc9beb113.jpg"
                alt="" />
        </article>
        <article className='h-40 overflow-hidden rounded-lg'>
            <img className='w-full h-full object-cover'
                src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRHCWWFoH41Wm59POvxQPtOWT6XmHovcViXTYe1HRVNol6cZorKouAmj4lOkOxtwnR3Agc&usqp=CAU"
                alt="" />
        </article>

        <article className='h-40 overflow-hidden rounded-lg'>
            <img className='w-full h-full object-cover'
                src="https://www.lavozdelsur.es/uploads/s1/11/22/25/9/1658619294066-01.jpeg" alt="" />
        </article>
        <article className='h-40 overflow-hidden rounded-lg'>
            <img className='w-full h-full object-cover'
                src="https://publicacionesdelsur.b-cdn.net/articulos/articulos-1027817.jpg" alt="" />
        </article>
        <article className='h-40 overflow-hidden rounded-lg'>
            <img className='w-full h-full object-cover'
                src="https://www.shutterstock.com/image-photo/two-young-woman-having-great-600nw-2195333383.jpg"
                alt="" />
        </article>
    </section>
</template>

<script>
export default {

}
</script>
