// next/src/app/register/page.jsx
'use client'
import Link from 'next/link';
import axios from 'axios';
import React, { useState, useEffect } from 'react';
import LoginMethods from '../components/LoginMethods'
import Loader from '../components/Loader'


const page = () => {
  const [email, setEmail] = useState('');
  const [name, setName] = useState('');
  const [surnames, setSurnames] = useState('');
  const [nickname, setNickname] = useState('');
  const [password, setPassword] = useState('');
  const [birthdate, setBirthdate] = useState('');
  const [passwordconfirmation, setConfirmPassword] = useState('');
  const [isLoading, setIsLoading] = useState(false);

  const register = async (event) => {
    event.preventDefault();
    setIsLoading(true);


    try {
      const response = await axios.post('http://localhost:8000/api/register', {
        email,
        name,
        surnames,
        nickname,
        password,
        birthdate,
        passwordconfirmation,
      });

      console.log(response.data);

    } catch (error) {
      console.error('Error fetching data:', error);
    }
    setIsLoading(false);

  };

  return (
    <main className='w-screen h-screen bg-background'>
      <section className='w-[80vw] h-screen mx-auto flex flex-col gap-10 justify-center'>
        <h1 className='text-4xl font-semibold'>Registra't</h1>
        <form className='flex flex-col gap-6' onSubmit={register}>
          <input className='bg-transparent border-b border-gray-400 outline-none' type="email" placeholder="Email" value={email} onChange={e => setEmail(e.target.value)} />
          <input className='bg-transparent border-b border-gray-400 outline-none' type="text" placeholder="Nom" value={name} onChange={e => setName(e.target.value)} />
          <input className='bg-transparent border-b border-gray-400 outline-none' type="text" placeholder="Cognoms" value={surnames} onChange={e => setSurnames(e.target.value)} />
          <input className='bg-transparent border-b border-gray-400 outline-none' type="text" placeholder="Usuari" value={nickname} onChange={e => setNickname(e.target.value)} />
          <input className='bg-transparent border-b border-gray-400 outline-none' type="date" placeholder="Data de naixement" value={birthdate} onChange={e => setBirthdate(e.target.value)} />
          <input className='bg-transparent border-b border-gray-400 outline-none' type="password" placeholder="Contrasenya" value={password} onChange={e => setPassword(e.target.value)} />
          <input className='bg-transparent border-b border-gray-400 outline-none' type="password" placeholder="Repeteix la contrasenya" value={passwordconfirmation} onChange={e => setConfirmPassword(e.target.value)} />
          <button className='flex justify-center py-3 font-bold rounded-full bg-gradient-to-r from-orange-600 to-yellow-600'>{!isLoading ? "Registra'm" : <Loader />}</button>
        </form>

        <LoginMethods forWhat="registra't" />

        <Link href="/join"><svg className='w-auto h-8' xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" strokeWidth="2" stroke="currentColor" fill="none" strokeLinecap="round" strokeLinejoin="round"><path stroke="none" d="M0 0h24v24H0z" fill="none" /><path d="M5 12l14 0" /><path d="M5 12l6 6" /><path d="M5 12l6 -6" /></svg></Link>
      </section>



    </main>
  )
}

export default page

// nuxt/pages/register.vue
<template>
    <main class='w-screen h-screen bg-background'>
        <section class='w-[80vw] h-screen mx-auto flex flex-col gap-10 justify-center'>
            <h1 class='text-4xl font-semibold text-white'>Registra't</h1>
            <form class="flex flex-col gap-6" @submit.prevent="register">
                <input class="bg-transparent border-b border-gray-400 outline-none text-white" type="email" placeholder="Email"
                    v-model="email" />
                <input class="bg-transparent border-b border-gray-400 outline-none text-white" type="text" placeholder="Nom"
                    v-model="name" />
                <input class="bg-transparent border-b border-gray-400 outline-none text-white" type="text" placeholder="Cognoms"
                    v-model="surnames" />
                <input class="bg-transparent border-b border-gray-400 outline-none text-white" type="text" placeholder="Usuari"
                    v-model="nickname" />
                <input class="bg-transparent border-b border-gray-400 outline-none text-white" type="date"
                    placeholder="Data de naixement" v-model="birthdate" />
                <input class="bg-transparent border-b border-gray-400 outline-none text-white" type="password"
                    placeholder="Contrasenya" v-model="password" />
                <input class="bg-transparent border-b border-gray-400 outline-none text-white" type="password"
                    placeholder="Repeteix la contrasenya" v-model="passwordconfirmation" />
                <button
                    class="flex justify-center py-3 font-bold rounded-full bg-gradient-to-r from-orange-600 to-yellow-600">
                    <span v-if="!isLoading" class="text-white">Registra'm</span>
                    <Loader v-else />
                </button>
            </form>

            <LoginMethods forWhat="registra't" />

            <NuxtLink href='/join' class='text-white'><svg class='w-auto h-8' xmlns="http://www.w3.org/2000/svg"
                    width="24" height="24" viewBox="0 0 24 24" strokeWidth="2" stroke="currentColor" fill="none"
                    strokeLinecap="round" strokeLinejoin="round">
                    <path stroke="none" d="M0 0h24v24H0z" fill="none" />
                    <path d="M5 12l14 0" />
                    <path d="M5 12l6 6" />
                    <path d="M5 12l6 -6" />
                </svg></NuxtLink>
        </section>



    </main>
</template>

<script>
import axios from 'axios';
import Loader from '~/components/Loader.vue';


export default {
    data() {
        return {
            email: '',
            name: '',
            surnames: '',
            nickname: '',
            birthdate: '',
            password: '',
            passwordconfirmation: '',
            isLoading: false,
        };
    },

    methods: {
        async register() {
            this.isLoading = true;

            try {
                const response = await axios.post('http://localhost:8000/api/register', {
                    email: this.email,
                    name: this.name,
                    surnames: this.surnames,
                    nickname: this.nickname,
                    password: this.password,
                    birthdate: this.birthdate,
                    passwordconfirmation: this.passwordconfirmation
                });
                store.setUserInfo({
                    id: response.data.data.user.id,
                    name: response.data.data.user.name,
                    surnames: response.data.data.user.surnames,
                    email: response.data.data.user.email,
                    token: response.data.data.token,
                });
                store.setLoggedIn(true);
                
                this.$router.push('/events');
                console.log(response.data);
            } catch (error) {
                console.error('Error fetching data:', error);
            }

            this.isLoading = false;
        }
    }
}
</script>
